language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hirokitominaga/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hirokitominaga/react-test npm test

after_success:
  - docker build -t hirokitominaga/multi-client ./client
  - docker build -t hirokitominaga/multi-nginx ./nginx
  - docker build -t hirokitominaga/multi-server ./server
  - docker build -t hirokitominaga/multi-server ./server
