language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hirokitominaga/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hirokitominaga/react-test npm test
after_success:
  - docker build -t hirokitominaga/multi-client ./client
  - docker build -t hirokitominaga/multi-nginx ./nginx
  - docker build -t hirokitominaga/multi-server ./server
  - docker build -t hirokitominaga/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hirokitominaga/multi-client
  - docker push hirokitominaga/multi-nginx
  - docker push hirokitominaga/multi-server
  - docker push hirokitominaga/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'ap-northeast-1'
  app: 'docker-multi-container-demo'
  env: 'Dockermulticontainerdemo-env'
  bucket_name: 'elasticbeanstalk-ap-northeast-1-580264286652'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $ACCESS_SECRET_KEY
